package config

const (
	APP_NAME                 = "APP_NAME"
	LOG_LEVEL                = "LOG_LEVEL"
	ENV                      = "ENV"
	PORT                     = "PORT"
	AWS_REGION               = "AWS_REGION"
	AWS_ENDPOINT             = "AWS_ENDPOINT"
	AWS_SECRET_PREFIX        = "AWS_SECRET_PREFIX"
	AWS_SECRET_BATCH         = "AWS_SECRET_BATCH"
	SEARCH_API_CLIENT_ID     = "SEARCH_API_CLIENT_ID"
	SEARCH_API_CLIENT_SECRET = "SEARCH_API_CLIENT_SECRET"
	TYPESENSE_HOST           = "TYPESENSE_HOST"
	TYPESENSE_PORT           = "TYPESENSE_PORT"
	TYPESENSE_API_KEY        = "TYPESENSE_API_KEY"
	TYPESENSE_COLLECTION     = "TYPESENSE_COLLECTION"
	IP_WHITELIST             = "IP_WHITELIST"
	IP_BLACKLIST             = "IP_BLACKLIST"
	RATE_LIMIT_RPS           = "RATE_LIMIT_RPS"
	RATE_LIMIT_BURST         = "RATE_LIMIT_BURST"
)
